matchTiles=minecraft:block/grass_block/grass_top1 minecraft:block/grass_block/grass_top2 minecraft:block/grass_block/grass_top3 
tiles=0-5
faces=top
method=overlay_random
connect=block
biomes=minecraft:swamp

# Overlay is not applied to 
# - grass_block_top
# - grass_top4
# - grass_top5 
# - grass_top6