# Stones
skins.1=100 101
maxHeight.1=01
weights.1=9 1

skins.2=101 102 103 104
maxHeight.2=55
weights.2=6 2 1 1

# Biomes Specific
skins.3=2 35
biomes.3=badlands eroded_badlands wooded_badlands
weights.3=1 3

skins.4=3
biomes.4=cherry_grove

skins.5=4
biomes.5=swamp

skins.6=5
biomes.6=mangrove_swamp

skins.7=6 30 31
biomes.7=desert savanna savanna_plateau windswept_savanna
weights.7=2 1 1

skins.8=6
biomes.8=nether_wastes soul_sand_valley crimson_forest warped_forest basalt_deltas

skins.9=7 101
biomes.9=stony_peaks
weights.9=7 3

skins.10=8
biomes.10=jungle bamboo_jungle

skins.11=9
biomes.11=sparse_jungle

skins.12=10
biomes.12=mushroom_fields

skins.13=11
biomes.13=plains sunflower_plains beach dripstone_caves

skins.14=12
biomes.14=forest flower_forest

skins.15=13
biomes.15=dark_forest

skins.16=14
biomes.16=birch_forest old_growth_birch_forest

skins.17=15
biomes.17=ocean deep_ocean warm_ocean lukewarm_ocean deep_lukewarm_ocean cold_ocean deep_cold_ocean deep_frozen_ocean river lush_caves the_end small_end_islands end_barrens end_midlands end_highlands the_void

skins.18=16
biomes.18=meadow

skins.19=17
biomes.19=old_growth_pine_taiga

skins.20=18
biomes.20=taiga old_growth_spruce_taiga

skins.21=19
biomes.21=windswept_hills windswept_gravelly_hills windswept_forest stony_shore

skins.22=20 30 31 40 41
biomes.22=snowy_beach
weights.23=2 1 1 1 1

skins.23=21 40 41
biomes.23=snowy_plains ice_spikes snowy_taiga frozen_ocean frozen_river grove snowy_slopes frozen_peaks jagged_peaks
weights.23=2 1 1

skins.24=1