
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.swem]
			whitewash = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.shineals_prehistoric_expansion]
			juniper = true
			ginkgo = true

		[types.wood_type.vampirism]
			dark_spruce = true
			cursed_spruce = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.prehistoricfauna]
			metasequoia = true
			araucaria = true
			protopiceoxylon = true
			zamites = true
			protojuniperoxylon = true
			agathoxylon = true
			heidiphyllum = true
			liriodendrites = true
			ginkgo = true
			trochodendroides = true
			brachyphyllum = true
			woodworthia = true
			schilderia = true
			dryophyllum = true
			taxodium = true
			sabalites = true
			platanites = true
			taxus = true
			czekanowskia = true
			schizolepidopsis = true
			podozamites = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.tconstruct]
			greenheart = true
			skyroot = true
			bloodshroom = true
			enderbark = true

	[types.stone_type]

		[types.stone_type.ars_nouveau]
			sourcestone = true

		[types.stone_type.rainbowreef]
			coralstone = true

		[types.stone_type.terramity]
			igneostone = true
			moonstone = true

		[types.stone_type.create]
			limestone = true
			asurine = true
			crimsite = true
			ochrum = true
			veridium = true
			scoria = true
			scorchia = true

		[types.stone_type.quark]
			soul_sandstone = true
			midori = true
			duskbound = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true
			shingles = true

		[types.stone_type.deeperdarker]
			sculk_stone = true
			gloomslate = true

		[types.stone_type.tconstruct]
			seared_stone = true
			scorched_stone = true

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true
			golden_apple_acacia = true
			golden_apple_birch = true
			golden_apple_dark_oak = true
			golden_apple_jungle = true
			golden_apple_oak = true
			golden_apple_spruce = true

		[types.leaves_type.shineals_prehistoric_expansion]
			juniper = true
			ginkgo = true

		[types.leaves_type.vampirism]
			dark_spruce = true

		[types.leaves_type.prehistoricfauna]
			metasequoia = true
			araucaria = true
			protopiceoxylon = true
			zamites = true
			protojuniperoxylon = true
			agathoxylon = true
			heidiphyllum = true
			liriodendrites = true
			ginkgo = true
			yellow_ginkgo = true
			trochodendroides = true
			brachyphyllum = true
			woodworthia = true
			schilderia = true
			dryophyllum = true
			taxodium = true
			sabalites = true
			sabalites_top = true
			platanites = true
			taxus = true
			czekanowskia = true
			schizolepidopsis = true
			podozamites = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.traversable_leaves]
			dev = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.tconstruct]
			earth_slime = true
			sky_slime = true
			ender_slime = true

	[types.mud_type]

		[types.mud_type.deeperdarker]
			sculk_grime = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			center_cut_log = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			firewood_log = true
			circle_glass_pane = true
			versailles_planks = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			planked_log = true
			mixed_log = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			line_bared_glass = true
			slanted_planks = true
			edge_cut_log = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			meshed_trapdoor = true
			overgrown_log = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			flowering_log = true
			double_herringbone_planks = true
			crated_planks = true
			horizontal_lined_glass = true
			reinforced_log = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			shack_door = true
			bundled_log = true
			polished_planks = true
			ornate_bared_glass_pane = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			damaged_log = true
			golden_barred_trapdoor = true
			nailed_log = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwstairs]
			terrace_stairs = true
			compact_stairs = true
			balcony = true
			loft_stairs = true
			railing = true
			platform = true
			skyline_stairs = true
			bulk_stairs = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			full_drawers_4 = true
			full_drawers_1 = true
			half_drawers_1 = true
			half_drawers_4 = true
			half_drawers_2 = true
			trim = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			vertical_slab = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.friendsandfoes]
			beehive = true

	[entries.stone_type]

		[entries.stone_type.rechiseled]
			squares = true
			smooth_large_tiles = true
			brick_paving_connecting = true
			brick_pattern_connecting = true
			brick_pattern = true
			waves_connecting = true
			small_bricks = true
			smooth_large_tiles_connecting = true
			small_bricks_connecting = true
			path_connecting = true
			bordered = true
			rotated_bricks_connecting = true
			smooth_rotated_bricks = true
			rotated_bricks = true
			big_tiles_connecting = true
			smooth_brick_paving = true
			diagonal_bricks = true
			big_tiles = true
			smooth_rotated_bricks_connecting = true
			tiles_connecting = true
			brick_paving = true
			small_tiles_connecting = true
			bordered_connecting = true
			waves = true
			crushed_connecting = true
			tiles = true
			squares_connecting = true
			path = true
			smooth_tiles_connecting = true
			diagonal_bricks_connecting = true
			smooth_tiles = true
			crushed = true
			small_tiles = true
			smooth_brick_paving_connecting = true
			slated = true

		[entries.stone_type.mcwroofs]
			top_roof = true
			bricks_attic_roof = true
			lower_roof = true
			upper_steep_roof = true
			steep_roof = true
			roof = true
			bricks_steep_roof = true
			bricks_roof = true
			bricks_lower_roof = true
			upper_lower_roof = true
			bricks_top_roof = true
			attic_roof = true
			bricks_upper_steep_roof = true
			bricks_upper_lower_roof = true

		[entries.stone_type.mcwstairs]
			mossy_brick_railing = true
			brick_skyline_stairs = true
			brick_bulk_stairs = true
			mossy_brick_balcony = true
			brick_terrace_stairs = true
			mossy_brick_loft_stairs = true
			brick_loft_stairs = true
			mossy_brick_platform = true
			brick_railing = true
			brick_compact_stairs = true
			brick_balcony = true
			brick_platform = true
			mossy_brick_skyline_stairs = true
			mossy_brick_compact_stairs = true
			mossy_brick_terrace_stairs = true
			mossy_brick_bulk_stairs = true

		[entries.stone_type.mcwbridges]
			balustrade_bricks_bridge = true
			mossy_bridge_pier = true
			mossy_brick_bridge = true
			bridge_pier = true
			mossy_bridge_stair = true
			balustrade_mossy_bricks_bridge = true
			brick_bridge_stair = true
			bridge = true
			brick_bridge = true

		[entries.stone_type.mcwfences]
			modern_wall = true
			modern_brick_wall = true
			railing_gate = true
			grass_topped_wall = true
			railing_wall = true
			railing_brick_wall = true
			brick_railing_gate = true
			pillar_wall = true

		[entries.stone_type.mcwwindows]
			pane_window = true
			window2 = true
			brick_arrow_slit = true
			four_window = true
			brick_gothic = true
			window = true

		[entries.stone_type.create]
			cut_wall = true
			cut_brick_slab = true
			polished_cut_slab = true
			small_brick_wall = true
			cut = true
			cut_stairs = true
			small_brick_stairs = true
			cut_bricks = true
			small_bricks = true
			layered = true
			cut_brick_wall = true
			pillar = true
			cut_brick_stairs = true
			polished_cut_wall = true
			cut_slab = true
			polished_cut = true
			small_brick_slab = true
			polished_cut_stairs = true

		[entries.stone_type.quark]
			vertical_slab = true
			polished_vertical_slab = true
			pillar = true

	[entries.leaves_type]

		[entries.leaves_type.mcwfences]
			hedge = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

