skins.1=2
name.1=ipattern:*Golden Allay*

skins.2=101
name.2=ipattern:*Black Allay*

skins.3=102
name.3=ipattern:*Blue Allay*

skins.4=103
name.4=ipattern:*Brown Allay*

skins.5=104
name.5=ipattern:*Cyan Allay*

skins.6=105
name.6=ipattern:*Gray Allay*

skins.7=106
name.7=ipattern:*Green Allay*

skins.8=107
name.8=ipattern:*Light Blue Allay*

skins.9=108
name.9=ipattern:*Light Gray Allay*

skins.10=109
name.10=ipattern:*Lime Allay*

skins.11=110
name.11=ipattern:*Magenta Allay*

skins.12=111
name.12=ipattern:*Orange Allay*

skins.13=112
name.13=ipattern:*Pink Allay*

skins.14=113
name.14=ipattern:*Purple Allay*

skins.15=114
name.15=ipattern:*Red Allay*

skins.16=115
name.16=ipattern:*White Allay*

skins.17=116
name.17=ipattern:*Yellow Allay*

skins.18=2 102 104 106 107 109 110 111 112 113 114
weights.18=3 1 1 1 1 1 1 1 1 1 1

skins.19=2-3
weights.19=3 10