skins.1=2
biomes.1=badlands eroded_badlands wooded_badlands

skins.2=3
biomes.2=cherry_grove

skins.3=4
biomes.3=swamp

skins.4=5
biomes.4=mangrove_swamp

skins.5=6
biomes.5=desert savanna savanna_plateau windswept_savanna nether_wastes soul_sand_valley crimson_forest warped_forest basalt_deltas

skins.6=7
biomes.6=stony_peaks

skins.7=8
biomes.7=jungle bamboo_jungle

skins.8=9
biomes.8=sparse_jungle

skins.9=10
biomes.9=mushroom_fields

skins.10=11
biomes.10=plains sunflower_plains beach dripstone_caves

skins.11=12
biomes.11=forest flower_forest

skins.12=13
biomes.12=dark_forest

skins.13=14
biomes.13=birch_forest old_growth_birch_forest

skins.14=15
biomes.14=ocean deep_ocean warm_ocean lukewarm_ocean deep_lukewarm_ocean cold_ocean deep_cold_ocean deep_frozen_ocean river lush_caves the_end small_end_islands end_barrens end_midlands end_highlands the_void

skins.15=16
biomes.15=meadow

skins.16=17
biomes.16=old_growth_pine_taiga

skins.17=18
biomes.17=taiga old_growth_spruce_taiga

skins.18=19
biomes.18=windswept_hills windswept_gravelly_hills windswept_forest stony_shore

skins.19=20
biomes.19=snowy_beach

skins.20=21
biomes.20=snowy_plains ice_spikes snowy_taiga frozen_ocean frozen_river grove snowy_slopes frozen_peaks jagged_peaks

skins.21=1