matchTiles=minecraft:block/grass_block/grass_block_side_overlay_40
method=random

tiles=10a
weights=1

faces=sides
tintIndex=1

biomes=badlands eroded_badlands wooded_badlands desert savanna savanna_plateau windswept_savanna