matchTiles=minecraft:block/grass_block/grass_block_side_40 minecraft:block/grass_block/grass_block_side_41 minecraft:block/grass_block/grass_block_side_42 minecraft:block/grass_block/grass_block_side_43
method=random

tiles=10 11 12 13
weights=1 1 1 1

faces=sides

biomes=badlands eroded_badlands wooded_badlands desert savanna savanna_plateau windswept_savanna