matchTiles=minecraft:block/grass_block/grass_block_side_21 minecraft:block/grass_block/grass_block_side_22 minecraft:block/grass_block/grass_block_side_23 minecraft:block/grass_block/grass_block_side_31 minecraft:block/grass_block/grass_block_side_32 minecraft:block/grass_block/grass_block_side_33
method=random

tiles=51 52 53 61 62 63
weights=1 1 1 1 1 1

faces=sides

biomes=forest flower_forest birch_forest old_growth_birch_forest dark_forest grove flower_forest river taiga snowy_taiga old_growth_pine_taiga old_growth_spruce_taiga