matchTiles=minecraft:block/grass_block/grass_block_side_overlay_20 minecraft:block/grass_block/grass_block_side_overlay_30
method=random

tiles=50a 60a
weights=1 1

faces=sides
tintIndex=1

biomes=forest flower_forest birch_forest old_growth_birch_forest dark_forest grove flower_forest river taiga snowy_taiga old_growth_pine_taiga old_growth_spruce_taiga