matchTiles=minecraft:block/grass_block/grass_block_side_overlay_20 minecraft:block/grass_block/grass_block_side_overlay_30 minecraft:block/grass_block/grass_block_side_overlay_40
method=random

tiles=50a 60a 70a 80a
weights= 6 6 3 6

faces=sides
TintIndex=1

biomes=bamboo_jungle jungle sparse_jungle mangrove_swamp swamp