matchTiles=minecraft:block/grass_block/grass_block_side_21 minecraft:block/grass_block/grass_block_side_22 minecraft:block/grass_block/grass_block_side_23 minecraft:block/grass_block/grass_block_side_31 minecraft:block/grass_block/grass_block_side_32 minecraft:block/grass_block/grass_block_side_33 minecraft:block/grass_block/grass_block_side_40 minecraft:block/grass_block/grass_block_side_41 minecraft:block/grass_block/grass_block_side_42 minecraft:block/grass_block/grass_block_side_43
method=random

tiles=51 52 53 61 62 63 71 72 73 81 82 83
weights= 2 2 2 2 2 2 1 1 1 2 2 2

faces=sides

biomes=bamboo_jungle jungle sparse_jungle mangrove_swamp swamp lush_caves